# Generated by Django 3.2.16 on 2022-10-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teamRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbmsapp.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('height', models.IntegerField()),
                ('number_of_matches', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('average', models.FloatField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to='bbmsapp.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('team_1_score', models.IntegerField()),
                ('team_2_score', models.IntegerField()),
                ('round', models.CharField(choices=[('Q', 'Qualifiers'), ('S8', 'Super 8'), ('SF', 'Semi-Final'), ('F', 'Finals')], default='Qualifiers', max_length=5)),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='bbmsapp.teams')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='bbmsapp.teams')),
                ('winning_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='bbmsapp.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('coaching_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_team_id', to='bbmsapp.teams')),
            ],
        ),
    ]
